baseURL: "https://tdoot.com/"
title: tdoot's odd little bazaar
paginate: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-Y62CJP0177

minify:
  disableXML: true
  minifyOutput: true

params:
  mainSections:
  - blog
  - photography
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: tdoot's odd little bazaar
  description: "keep your expectations low and i may surprise you"
  keywords: [Blog, Portfolio, Technology"]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["/images/pictures/portrait.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/icons/favicon.ico"
    favicon16x16: "/images/icons/favicon-16x16.png"
    favicon32x32: "/images/icons/favicon-32x32.png"
    apple_touch_icon: "/images/icons/apple-touch-icon.png"
    safari_pinned_tab: "/images/icons/apple-touch-icon.png"

  label:
    text: "Home"
    icon: /images/icons/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: heads up..
    subtitle: "no money back guarantee here"
    imageUrl: /images/pictures/portrait.jpg
    imageWidth: 100
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "here be dragons"
    Content: |
      these are my scattered thoughts - no money back guarantee here.

      you can also find me on [cohost](https://cohost.org/tdoot)

  socialIcons:
    - name: github
      url: "https://github.com/tonydelanuez"
    - name: mastodon
      url: "https://macaw.social/@tdoot"
    - name: twitter
      url: "https://twitter.com/tdelanuez"
    - name: goodreads
      url: "https://literal.club/tdoot"
    - name: flickr
      url: "https://flickr.com/tonydelanuez"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/tonydelanuez/tonydelanuez.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: blog
      url: /categories/blog
      weight: 1
    - identifier: photography
      name: photos
      url: /categories/photography
      weight: 2
    - identifier: categories
      name: categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: tags
      url: /tags/
      weight: 4
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai